#pragma config(Sensor, S2,     US,             sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          LeftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorB,          RightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define THRESHOLD		90

void drive(int speed)
{
	// move both motors in the same direction
  // speed is an int between 0-100%, negative for reverse
	setMotorSpeed(LeftMotor, speed);
	setMotorSpeed(RightMotor, speed);

	display_motor_states(speed, speed);
}

void turn(int speed)
{
	// move both motors in the opposite direction to rotate the robot
  // speed is an int between 0-100%, positive for clockwise, negative for anti-clockwise
	setMotorSpeed(LeftMotor, speed);
	setMotorSpeed(RightMotor, -speed);

	display_motor_states(speed, -speed);
}

void stopRobot(void)
{
	// stop the robot's motors from moving
	setMotorSpeed(LeftMotor, 0);
	setMotorSpeed(RightMotor, 0);
}

void display_motor_states(int left_speed, int right_speed)
{
	displayCenteredTextLine(4, "Left motor: %d%%", left_speed);
	displayCenteredTextLine(5, "Right motor: %d%%", right_speed);
}

enum States {
	SEARCHING,
	REFINING,
	MOVING,
}

void refine_angle()
{
	int min_distance, new_distance;
	min_distance = getUSDistance(US);
	turn(0.1);
	while(1)
	{
		new_distance = getUSDistance(US);
		if (new_distance < min_distance) {
			break;
		}
	}
}

task main()
{
	int distance = 0;

	// Target search protocol

	turn(20);

	while(1)
	{
		while(1)
		{
			distance = getUSDistance(US);
			if (distance < THRESHOLD)
			{
				displayCenteredBigTextLine(4, "Target Aquired");
				stopRobot();
				drive();
				break;
			}
			else {
				displayCenteredBigTextLine(4, "Searching");
			}
		}
		while(1)
		{
			distance = getUSDistance(US);
			if (distance > THRESHOLD)
			{
				displayCenteredBigTextLine(4, "Target Lost");
				stopRobot();
				turn(20);
				break;
			}
			else {
				displayCenteredBigTextLine(4, "Moving");
			}
		}
	}
}